// ─── NAVIGATION CONFIG ──────────────────────────────────────────────────────
// Fuente de verdad de la navegación del backoffice.
// Define sidebar, grupos, cockpit y estado de implementación de cada módulo.
// NO contiene lógica de negocio ni lógica de UI.

import type { NavGroup, CockpitModuleConfig } from './types';
import {
  OPS_ROLES,
  FINANCE_ROLES,
  DIRECCION_ROLES,
  REPORTING_ROLES,
  PERITO_ACCESS,
  OPERARIO_ACCESS,
} from './permissions';

// ─── COCKPIT SUPERIOR (3 módulos grandes) ────────────────────────────────────

export const COCKPIT_MODULES: CockpitModuleConfig[] = [
  {
    id: 'asignaciones',
    label: 'Asignaciones',
    path: '/asignaciones',
    icon: 'Inbox',
    feedKey: 'asignaciones',
    variant: 'blue',
    quickFilters: [
      { label: 'Sin asignar', value: 'NO_ASIGNADO' },
      { label: 'En planificación', value: 'EN_PLANIFICACION' },
      { label: 'Urgentes', value: 'urgente' },
      { label: 'Vencidos', value: 'vencido' },
    ],
    status: 'partial',
  },
  {
    id: 'solicitudes',
    label: 'Solicitudes / Avisos',
    path: '/solicitudes',
    icon: 'Bell',
    feedKey: 'solicitudes',
    variant: 'amber',
    quickFilters: [
      { label: 'Pendientes', value: 'pendiente' },
      { label: 'Urgentes', value: 'urgente' },
      { label: 'Hoy', value: 'hoy' },
    ],
    status: 'partial',
  },
  {
    id: 'trabajos_no_revisados',
    label: 'Trabajos no revisados',
    path: '/partes-validacion',
    icon: 'ClipboardCheck',
    feedKey: 'trabajos_no_revisados',
    variant: 'red',
    quickFilters: [
      { label: 'Pendientes', value: 'pendiente' },
      { label: 'Rechazados', value: 'rechazado' },
    ],
    status: 'implemented',
  },
];

// ─── SIDEBAR — GRUPOS Y ENTRADAS ─────────────────────────────────────────────

export const NAV_GROUPS: NavGroup[] = [
  // ── ENTRADA ──────────────────────────────────────────────────────────────
  {
    id: 'entrada',
    label: 'Entrada',
    icon: 'Inbox',
    defaultOpen: true,
    entries: [
      {
        id: 'asignaciones',
        label: 'Asignaciones',
        path: '/asignaciones',
        icon: 'Inbox',
        badge: { key: 'asignaciones', variant: 'info', hideWhenZero: true },
        status: 'partial',
        description: 'Expedientes sin asignar o en planificación pendientes de acción',
      },
      {
        id: 'solicitudes',
        label: 'Solicitudes / Avisos',
        path: '/solicitudes',
        icon: 'Bell',
        badge: { key: 'solicitudes', variant: 'warning', hideWhenZero: true },
        status: 'partial',
        description: 'Alertas, avisos y solicitudes entrantes',
      },
      {
        id: 'comunicaciones',
        label: 'Comunicaciones',
        path: '/comunicaciones',
        icon: 'MessageSquare',
        badge: { key: 'comunicaciones', variant: 'default', hideWhenZero: true },
        status: 'partial',
        description: 'Bandeja de comunicaciones con asegurados y compañías',
      },
    ],
  },

  // ── OPERACIONES ───────────────────────────────────────────────────────────
  {
    id: 'operaciones',
    label: 'Operaciones',
    icon: 'FolderOpen',
    defaultOpen: true,
    entries: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        path: '/dashboard',
        icon: 'LayoutDashboard',
        status: 'implemented',
        description: 'Panel de mando con KPIs operativos y financieros',
      },
      {
        id: 'siniestros',
        label: 'Siniestros',
        path: '/expedientes',
        icon: 'FolderOpen',
        status: 'implemented',
        description: 'Todos los expedientes del ERP (vista general)',
      },
      {
        id: 'siniestros-activos',
        label: 'Activos',
        path: '/servicios/activos',
        icon: 'Activity',
        status: 'implemented',
        description: 'Expedientes activos — vista operativa con 15 columnas, 11 filtros y semáforos de fecha espera',
      },
      {
        id: 'siniestros-finalizados',
        label: 'Finalizados',
        path: '/servicios/finalizados',
        icon: 'CheckCircle',
        status: 'implemented',
        description: 'Expedientes finalizados con sub-tabla de facturas y estados de cobro',
      },
      {
        id: 'partes-validacion',
        label: 'Trabajos no revisados',
        path: '/partes-validacion',
        icon: 'ClipboardCheck',
        badge: { key: 'partes_pendientes', variant: 'danger', hideWhenZero: true },
        status: 'implemented',
        description: 'Partes de operario pendientes de validación',
      },
      {
        id: 'informes-caducados',
        label: 'Informes caducados',
        path: '/informes-caducados',
        icon: 'AlertTriangle',
        badge: { key: 'informes_caducados', variant: 'warning', hideWhenZero: true },
        status: 'implemented',
        description: 'Citas con visita realizada sin informe presentado',
      },
      {
        id: 'presupuestos',
        label: 'Presupuestos',
        path: '/presupuestos',
        icon: 'FileText',
        status: 'partial',
        description: 'Lista de presupuestos (detalle ya implementado)',
      },
    ],
  },

  // ── PLANNING ──────────────────────────────────────────────────────────────
  {
    id: 'planning',
    label: 'Planning',
    icon: 'Calendar',
    defaultOpen: false,
    entries: [
      {
        id: 'agenda-mensual',
        label: 'Agenda mensual',
        path: '/planning/agenda',
        icon: 'CalendarDays',
        status: 'new',
        description: 'Agenda operativa mensual de citas y visitas',
      },
      {
        id: 'vp-agenda',
        label: 'VP Agenda',
        path: '/videoperitaciones/agenda',
        icon: 'Video',
        status: 'implemented',
        description: 'Agenda de videoperitaciones programadas',
      },
      {
        id: 'vp-lista',
        label: 'Videoperitaciones',
        path: '/videoperitaciones',
        icon: 'Monitor',
        status: 'implemented',
        description: 'Lista de videoperitaciones activas y pendientes',
      },
      {
        id: 'vp-pendientes',
        label: 'VP Pendientes contacto',
        path: '/videoperitaciones/pendientes',
        icon: 'PhoneMissed',
        status: 'implemented',
        description: 'Videoperitaciones pendientes de primer contacto',
      },
      {
        id: 'planning-geografico',
        label: 'Planning geográfico',
        path: '/planning/geo',
        icon: 'MapPin',
        status: 'implemented',
        description: 'Mapa operativo de expedientes, operarios y Smart Dispatch',
      },
    ],
  },

  // ── RED EXTERNA ───────────────────────────────────────────────────────────
  {
    id: 'red-externa',
    label: 'Red externa',
    icon: 'Users',
    defaultOpen: false,
    entries: [
      {
        id: 'operarios',
        label: 'Operarios',
        path: '/operarios-config',
        icon: 'HardHat',
        roles: OPERARIO_ACCESS,
        status: 'partial',
        description: 'Gestión de operarios propios y subcontratados',
      },
      {
        id: 'proveedores',
        label: 'Proveedores',
        path: '/proveedores',
        icon: 'Truck',
        status: 'implemented',
        description: 'Catálogo de proveedores de materiales y servicios',
      },
      {
        id: 'peritos',
        label: 'Peritos',
        path: '/peritos/admin',
        icon: 'UserSearch',
        roles: PERITO_ACCESS,
        status: 'implemented',
        description: 'Gestión de peritos y asignación de expedientes',
      },
      {
        id: 'peritos-expedientes',
        label: 'Mis expedientes (Perito)',
        path: '/peritos/expedientes',
        icon: 'ClipboardList',
        roles: ['perito', 'admin', 'supervisor'],
        status: 'implemented',
        description: 'Expedientes asignados al perito autenticado',
      },
      {
        id: 'peritos-dictamenes',
        label: 'Dictámenes',
        path: '/peritos/dictamenes',
        icon: 'Scale',
        roles: PERITO_ACCESS,
        status: 'implemented',
        description: 'Informes de valoración y dictámenes periciales',
      },
      {
        id: 'clientes',
        label: 'Clientes / Intervinientes',
        path: '/clientes',
        icon: 'UserCircle',
        status: 'new',
        description: 'Asegurados, propietarios y terceros intervinientes',
      },
      {
        id: 'rentings',
        label: 'Rentings',
        path: '/rentings',
        icon: 'Building2',
        featureFlag: 'rentings',
        status: 'new',
        description: 'Gestión de contratos de renting asociados a siniestros',
      },
    ],
  },

  // ── BUZÓN CORREO ──────────────────────────────────────────────────────────
  {
    id: 'correo',
    label: 'Buzón Correo',
    icon: 'Mail',
    defaultOpen: false,
    roles: OPS_ROLES,
    entries: [
      {
        id: 'correo-cuentas',
        label: 'Cuentas correo',
        path: '/correo/cuentas',
        icon: 'AtSign',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Cuentas IMAP/SMTP configuradas para el sistema',
      },
      {
        id: 'correo-configuracion',
        label: 'Configuración correo',
        path: '/correo/configuracion',
        icon: 'Settings2',
        roles: ['admin', 'supervisor'],
        status: 'new',
        description: 'SMTP, Resend, plantillas y reglas de enrutamiento',
      },
    ],
  },

  // ── FINANZAS ──────────────────────────────────────────────────────────────
  {
    id: 'finanzas',
    label: 'Finanzas',
    icon: 'DollarSign',
    defaultOpen: false,
    roles: FINANCE_ROLES,
    entries: [
      {
        id: 'pendientes-facturar',
        label: 'Pendientes de facturar',
        path: '/pendientes-facturar',
        icon: 'Receipt',
        badge: { key: 'facturas_pendientes', variant: 'warning', hideWhenZero: true },
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Expedientes finalizados pendientes de emitir factura',
      },
      {
        id: 'facturas',
        label: 'Facturas',
        path: '/facturas',
        icon: 'FileText',
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Listado de facturas emitidas',
      },
      {
        id: 'facturas-caducadas',
        label: 'Facturas caducadas',
        path: '/facturas-caducadas',
        icon: 'FileMinus',
        badge: { key: 'facturas_caducadas', variant: 'danger', hideWhenZero: true },
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Facturas vencidas sin cobrar o con anomalías',
      },
      {
        id: 'autofacturas',
        label: 'Autofacturas',
        path: '/autofacturas',
        icon: 'RefreshCw',
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Autofacturas de operarios y peritos',
      },
      {
        id: 'pedidos',
        label: 'Pedidos',
        path: '/pedidos',
        icon: 'ShoppingCart',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Órdenes de compra de materiales a proveedores',
      },
      {
        id: 'pedidos-recoger',
        label: 'Pedidos a recoger',
        path: '/pedidos/a-recoger',
        icon: 'Package',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Materiales pendientes de recogida en almacén',
      },
      {
        id: 'pedidos-caducados',
        label: 'Pedidos caducados',
        path: '/pedidos/caducados',
        icon: 'PackageX',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Pedidos sin gestionar fuera de plazo',
      },
      {
        id: 'config-emision',
        label: 'Config. emisión',
        path: '/config-emision',
        icon: 'Layers',
        roles: ['admin', 'financiero', 'supervisor'],
        status: 'implemented',
        description: 'Series, numeración, asignaciones, cuentas bancarias y config. de emisión por empresa',
      },
      {
        id: 'series-facturacion',
        label: 'Series facturación',
        path: '/series-facturacion',
        icon: 'Hash',
        roles: ['admin', 'financiero', 'supervisor'],
        status: 'partial',
        description: 'Configuración de series y numeración de facturas por empresa',
      },
      {
        id: 'bancos',
        label: 'Bancos',
        path: '/bancos',
        icon: 'Landmark',
        roles: FINANCE_ROLES,
        featureFlag: 'bancos',
        status: 'partial',
        description: 'Cuentas bancarias y conciliación de cobros',
      },
    ],
  },

  // ── CONTROL ───────────────────────────────────────────────────────────────
  {
    id: 'control',
    label: 'Control',
    icon: 'Sliders',
    defaultOpen: false,
    entries: [
      {
        id: 'baremos',
        label: 'Baremos',
        path: '/baremos',
        icon: 'BookOpen',
        roles: ['admin', 'supervisor', 'tramitador', 'financiero'],
        status: 'implemented',
        description: 'Catálogo de baremos y tarifas de trabajo',
      },
      {
        id: 'tareas',
        label: 'Tareas',
        path: '/tareas',
        icon: 'CheckSquare',
        badge: { key: 'tareas', variant: 'info', hideWhenZero: true },
        status: 'implemented',
        description: 'Gestión de tareas internas y externas',
      },
      {
        id: 'eventos',
        label: 'Eventos / Automatizaciones',
        path: '/eventos',
        icon: 'Zap',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Reglas de negocio, triggers y automatizaciones del ERP',
      },
      {
        id: 'mensajes-predefinidos',
        label: 'Mensajes predefinidos',
        path: '/mensajes-predefinidos',
        icon: 'MessageCircle',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Plantillas de comunicación para email y SMS con variables dinámicas',
      },
      {
        id: 'encuestas',
        label: 'Encuestas',
        path: '/encuestas',
        icon: 'ClipboardList',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Encuestas de satisfacción de cliente (post-cierre)',
      },
      {
        id: 'condiciones-control',
        label: 'Condiciones Presupuestos',
        path: '/condiciones-presupuestos',
        icon: 'FileText',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Textos de condiciones para presupuestos',
      },
      {
        id: 'lineas-facturacion',
        label: 'Líneas de Facturación',
        path: '/lineas-facturacion',
        icon: 'Receipt',
        roles: ['admin', 'supervisor', 'financiero'],
        status: 'implemented',
        description: 'Catálogo de conceptos reutilizables en presupuestos y facturas',
      },
      {
        id: 'documentos',
        label: 'Plantillas Documentos',
        path: '/control/documentos',
        icon: 'FolderArchive',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Plantillas de documentos para expedientes, presupuestos y comunicaciones',
      },
      {
        id: 'gestion-campos',
        label: 'Gestión de Campos',
        path: '/control/campos',
        icon: 'LayoutTemplate',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Grupos y campos personalizados para entidades del ERP',
      },
      {
        id: 'auditoria',
        label: 'Auditoría',
        path: '/control/auditoria',
        icon: 'Shield',
        roles: ['admin', 'supervisor', 'direccion'],
        status: 'new',
        description: 'Trazabilidad de acciones y log de auditoría del sistema',
      },
    ],
  },

  // ── CONFIGURACIÓN ─────────────────────────────────────────────────────────
  {
    id: 'configuracion',
    label: 'Configuración',
    icon: 'Settings',
    defaultOpen: false,
    roles: ['admin', 'supervisor'],
    entries: [
      {
        id: 'usuarios-roles',
        label: 'Tramitadores',
        path: '/usuarios',
        icon: 'UserCog',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Alta, edición y configuración de tramitadores internos',
      },
      {
        id: 'cargas-trabajo',
        label: 'Cargas de trabajo',
        path: '/usuarios/cargas',
        icon: 'LayoutDashboard',
        roles: ['admin', 'supervisor', 'direccion'],
        status: 'implemented',
        description: 'Dashboard de carga actual por tramitador en tiempo real',
      },
      {
        id: 'cola-asignacion',
        label: 'Cola de asignación',
        path: '/usuarios/cola',
        icon: 'ListOrdered',
        roles: ['admin', 'supervisor'],
        badge: { key: 'cola_asignacion', variant: 'warning', hideWhenZero: true },
        status: 'implemented',
        description: 'Expedientes sin tramitador asignado pendientes de gestión',
      },
      {
        id: 'reglas-reparto',
        label: 'Reglas de reparto',
        path: '/usuarios/reglas-reparto',
        icon: 'Shuffle',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Algoritmos de asignación automática y preasignaciones',
      },
      {
        id: 'companias',
        label: 'Compañías / Corredores / AF',
        path: '/companias',
        icon: 'Building',
        roles: ['admin', 'supervisor'],
        status: 'partial',
        description: 'Entidades aseguradoras, corredores y agencias franquiciadas',
      },
      {
        id: 'empresas',
        label: 'Empresas',
        path: '/empresas',
        icon: 'Briefcase',
        roles: ['admin', 'supervisor'],
        status: 'partial',
        description: 'Empresas facturadoras propias del grupo',
      },
      {
        id: 'especialidades',
        label: 'Especialidades',
        path: '/especialidades',
        icon: 'Wrench',
        roles: ['admin', 'supervisor'],
        status: 'partial',
        description: 'Tipos de siniestro, especialidades técnicas y gremios',
      },
      {
        id: 'calendario',
        label: 'Festivos',
        path: '/festivos',
        icon: 'CalendarRange',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Calendario de festivos nacionales, autonómicos y de empresa',
      },
      {
        id: 'comerciales',
        label: 'Comerciales',
        path: '/comerciales',
        icon: 'UserPlus',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Agentes comerciales e intermediarios del sistema',
      },
      {
        id: 'gestor-tipos',
        label: 'Gestor de Tipos',
        path: '/gestor-tipos',
        icon: 'Tag',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Tipos y etiquetas de clasificación de siniestros',
      },
      {
        id: 'doc-requerida',
        label: 'Doc. Requerida',
        path: '/doc-requerida',
        icon: 'FileCheck2',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Tipos de documentos exigidos a los operarios',
      },
      {
        id: 'autocita',
        label: 'Autocita',
        path: '/autocita',
        icon: 'Link',
        roles: ['admin', 'supervisor'],
        featureFlag: 'autocita',
        status: 'partial',
        description: 'Configuración del portal de autocita para asegurados',
      },
      {
        id: 'condiciones-presupuestos',
        label: 'Condiciones Presupuestos',
        path: '/condiciones-presupuestos',
        icon: 'FileText',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Textos de condiciones incluidos en presupuestos',
      },
      {
        id: 'centralita',
        label: 'Centralita',
        path: '/centralita',
        icon: 'Phone',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Registro de llamadas e integración de centralita',
      },
      {
        id: 'rgpd',
        label: 'RGPD',
        path: '/rgpd',
        icon: 'Shield',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Configuración de protección de datos y derechos de supresión',
      },
      {
        id: 'auto-visitas',
        label: 'Auto Visitas',
        path: '/auto-visitas',
        icon: 'Link2',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Portal de cita automática para asegurados',
      },
      {
        id: 'acerca-de',
        label: 'Acerca de GUAI ERP',
        path: '/acerca-de',
        icon: 'Info',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Versión del sistema, stack tecnológico y soporte',
      },
    ],
  },

  // ── SERVICIOS (módulo operaciones — réplica del ERP legacy) ───────────────
  {
    id: 'servicios',
    label: 'Servicios',
    icon: 'Briefcase',
    defaultOpen: false,
    entries: [
      // — Escritorio —
      {
        id: 'svc-escritorio',
        label: 'Escritorio',
        path: '/servicios/escritorio',
        icon: 'LayoutDashboard',
        status: 'partial',
        description: 'Dashboard del módulo: compañías con conteo de siniestros, filtro y ordenación',
      },
      // — Apertura —
      {
        id: 'svc-apertura',
        label: 'Apertura',
        path: '/expedientes/nuevo',
        icon: 'FilePlus',
        status: 'implemented',
        description: 'Formulario de alta / apertura de un nuevo siniestro',
      },
      // — Siniestros —
      {
        id: 'svc-activos',
        label: 'Activos',
        path: '/servicios/activos',
        icon: 'Activity',
        status: 'implemented',
        description: 'Listado de siniestros activos en curso',
      },
      {
        id: 'svc-finalizados',
        label: 'Finalizados',
        path: '/servicios/finalizados',
        icon: 'CheckCircle2',
        status: 'implemented',
        description: 'Listado de siniestros finalizados / cerrados',
      },
      // — Planning —
      {
        id: 'svc-planning',
        label: 'Planning',
        path: '/planning',
        icon: 'CalendarDays',
        status: 'partial',
        description: 'Planning mensual de visitas y trabajos de operarios',
      },
      {
        id: 'svc-bloqueos',
        label: 'Bloqueos',
        path: '/planning/bloqueos',
        icon: 'Lock',
        status: 'new',
        description: 'Gestión de bloqueos de disponibilidad en el planning (vacaciones, bajas)',
      },
      // — Planning Geográfico —
      {
        id: 'svc-planning-geo',
        label: 'Planning Geográfico',
        path: '/planning/geo',
        icon: 'MapPin',
        status: 'implemented',
        description: 'Mapa geográfico con filtros para distribución de siniestros y operarios',
      },
      // — Informes (48) —
      {
        id: 'svc-inf-urgencias',
        label: 'Urgencias Asignadas',
        path: '/servicios/informes/urgencias-asignadas',
        icon: 'AlertCircle',
        status: 'new',
        description: 'Eli Roque: urgencias asignadas por compañía y tramitador',
      },
      {
        id: 'svc-inf-albaranes',
        label: 'Albaranes',
        path: '/servicios/informes/albaranes',
        icon: 'ClipboardList',
        status: 'new',
        description: 'Informe de albaranes de trabajos y materiales',
      },
      {
        id: 'svc-inf-autof-operarios',
        label: 'Autofacturación Operarios',
        path: '/servicios/informes/autofacturacion-operarios',
        icon: 'Receipt',
        status: 'implemented',
        description: 'Autofacturación y liquidación de operarios',
      },
      {
        id: 'svc-inf-autof-comerciales',
        label: 'Autofacturación Comerciales',
        path: '/servicios/informes/autofacturacion-comerciales',
        icon: 'Receipt',
        status: 'new',
        description: 'Autofacturación y liquidación de agentes comerciales',
      },
      {
        id: 'svc-inf-facturacion',
        label: 'Facturación',
        path: '/servicios/informes/facturacion',
        icon: 'FileText',
        status: 'implemented',
        description: 'Informe de facturación por compañía, período y estado',
      },
      {
        id: 'svc-inf-fichajes',
        label: 'Fichajes de Usuarios',
        path: '/servicios/informes/fichajes-usuarios',
        icon: 'Clock',
        status: 'new',
        description: 'Registro de fichajes de entrada y salida del personal',
      },
      {
        id: 'svc-inf-graficas',
        label: 'Gráficas de Parámetros',
        path: '/servicios/informes/graficas-parametros',
        icon: 'LineChart',
        status: 'new',
        description: 'Visualización gráfica de parámetros operativos clave',
      },
      {
        id: 'svc-inf-cobros',
        label: 'Importación de Cobros',
        path: '/servicios/informes/importacion-cobros',
        icon: 'Download',
        status: 'new',
        description: 'Importación masiva de cobros desde ficheros bancarios',
      },
      {
        id: 'svc-inf-actividad',
        label: 'Actividad Tramitadores',
        path: '/servicios/informes/actividad-tramitadores',
        icon: 'BarChart2',
        status: 'partial',
        description: 'Actividad y productividad de tramitadores',
      },
      {
        id: 'svc-inf-agendas',
        label: 'Agendas',
        path: '/servicios/informes/agendas',
        icon: 'CalendarCheck',
        status: 'new',
        description: 'Informe de citas y visitas agendadas por período',
      },
      {
        id: 'svc-inf-autovisitas',
        label: 'Autovisitas',
        path: '/servicios/informes/autovisitas',
        icon: 'Link2',
        status: 'new',
        description: 'Informe de visitas realizadas a través del portal de autocita',
      },
      {
        id: 'svc-inf-baremos',
        label: 'Baremos Facturados',
        path: '/servicios/informes/baremos',
        icon: 'BookOpen',
        status: 'new',
        description: 'Baremos facturados por expediente, operario y compañía',
      },
      {
        id: 'svc-inf-cobros-grupo',
        label: 'Cobros del Grupo',
        path: '/servicios/informes/cobros-grupo',
        icon: 'Landmark',
        status: 'new',
        description: 'Informe consolidado de cobros del grupo Apuyen',
      },
      {
        id: 'svc-inf-colores',
        label: 'Colores de Facturación',
        path: '/servicios/informes/colores-facturacion',
        icon: 'Palette',
        status: 'new',
        description: 'Facturación segmentada por código de color',
      },
      {
        id: 'svc-inf-costes-medios',
        label: 'Costes Medios',
        path: '/servicios/informes/costes-medios',
        icon: 'TrendingDown',
        status: 'new',
        description: 'Análisis de costes medios por tipo de siniestro y compañía',
      },
      {
        id: 'svc-inf-encuestas',
        label: 'Encuestas',
        path: '/servicios/informes/encuestas',
        icon: 'Star',
        status: 'new',
        description: 'Resultados de encuestas de satisfacción post-servicio',
      },
      {
        id: 'svc-inf-gremios',
        label: 'Gremios por Expediente',
        path: '/servicios/informes/gremios-expediente',
        icon: 'Wrench',
        status: 'new',
        description: 'Distribución de expedientes por gremio o especialidad',
      },
      {
        id: 'svc-inf-incidencias',
        label: 'Incidencias',
        path: '/servicios/informes/incidencias',
        icon: 'AlertTriangle',
        status: 'new',
        description: 'Registro y análisis de incidencias en expedientes',
      },
      {
        id: 'svc-inf-llamadas',
        label: 'Llamadas',
        path: '/servicios/informes/llamadas',
        icon: 'Phone',
        status: 'new',
        description: 'Log de llamadas entrantes y salientes registradas',
      },
      {
        id: 'svc-inf-rent-global',
        label: 'Rentabilidad Global',
        path: '/servicios/informes/rentabilidad-global',
        icon: 'TrendingUp',
        status: 'implemented',
        description: 'Análisis de rentabilidad global de la operación',
      },
      {
        id: 'svc-inf-rent-global-fact',
        label: 'Rentabilidad Global Facturación',
        path: '/servicios/informes/rentabilidad-global-facturacion',
        icon: 'TrendingUp',
        status: 'new',
        description: 'Rentabilidad desde la perspectiva de facturación',
      },
      {
        id: 'svc-inf-especialidad',
        label: 'Especialidad Pendiente',
        path: '/servicios/informes/especialidad-pendiente',
        icon: 'ListTodo',
        status: 'new',
        description: 'Servicios de especialidades específicas pendientes',
      },
      {
        id: 'svc-inf-siniestros',
        label: 'Informe de Siniestros',
        path: '/servicios/informes/siniestros',
        icon: 'FolderOpen',
        status: 'new',
        description: 'Informe maestro de siniestros por compañía y período',
      },
      {
        id: 'svc-inf-tiempos-visita',
        label: 'Tiempos Visita Operario/Gremio',
        path: '/servicios/informes/tiempos-visita',
        icon: 'Timer',
        status: 'new',
        description: 'Tiempos de visita por operario y gremio',
      },
      {
        id: 'svc-inf-tiempos-autonomos',
        label: 'Tiempos/Costes Autónomos',
        path: '/servicios/informes/tiempos-autonomos',
        icon: 'UserCheck',
        status: 'new',
        description: 'Tiempos y costes de operarios autónomos',
      },
      {
        id: 'svc-inf-tiempos-contratados',
        label: 'Tiempos/Costes Contratados',
        path: '/servicios/informes/tiempos-contratados',
        icon: 'Users',
        status: 'new',
        description: 'Tiempos y costes de operarios en plantilla',
      },
      {
        id: 'svc-inf-tipos-dano',
        label: 'Tipos de Daño',
        path: '/servicios/informes/tipos-dano',
        icon: 'ShieldAlert',
        status: 'new',
        description: 'Distribución de expedientes por tipo de daño declarado',
      },
      {
        id: 'svc-inf-trabajos-op',
        label: 'Trabajos de Operarios',
        path: '/servicios/informes/trabajos-operarios',
        icon: 'HardHat',
        status: 'new',
        description: 'Trabajos realizados por operario en un período',
      },
      {
        id: 'svc-inf-trabajos-exp',
        label: 'Trabajos por Expediente',
        path: '/servicios/informes/trabajos-expediente',
        icon: 'FolderSearch',
        status: 'new',
        description: 'Detalle de todos los trabajos realizados por expediente',
      },
      {
        id: 'svc-inf-tramitacion',
        label: 'Tramitación',
        path: '/servicios/informes/tramitacion',
        icon: 'ArrowRightCircle',
        status: 'new',
        description: 'Estado de tramitación del portfolio de expedientes',
      },
      {
        id: 'svc-inf-geografico',
        label: 'Informe Geográfico',
        path: '/servicios/informes/geografico',
        icon: 'Map',
        status: 'new',
        description: 'Distribución geográfica de siniestros por provincia y CP',
      },
      {
        id: 'svc-inf-pedidos',
        label: 'Pedidos',
        path: '/servicios/informes/pedidos',
        icon: 'ShoppingCart',
        status: 'partial',
        description: 'Estado del portfolio de pedidos de material',
      },
      {
        id: 'svc-inf-planning-op',
        label: 'Planning Operario',
        path: '/servicios/informes/planning-operario',
        icon: 'CalendarRange',
        status: 'new',
        description: 'Planning individual de cada operario con ratios de ocupación',
      },
      {
        id: 'svc-inf-personalizados',
        label: 'Informes Personalizados',
        path: '/servicios/informes/personalizados',
        icon: 'SlidersHorizontal',
        status: 'new',
        description: 'Constructor de informes con filtros y columnas configurables',
      },
      {
        id: 'svc-inf-clientes',
        label: 'Listado de Clientes',
        path: '/servicios/informes/listado-clientes',
        icon: 'UserCircle',
        status: 'new',
        description: 'Directorio completo de asegurados y clientes',
      },
      {
        id: 'svc-inf-cuentas-activos',
        label: 'Cuentas Siniestros Activos',
        path: '/servicios/informes/cuentas-activos',
        icon: 'Wallet',
        status: 'new',
        description: 'Cuentas bancarias asociadas a siniestros activos',
      },
      {
        id: 'svc-inf-prevision-costes',
        label: 'Previsión de Costes Medios',
        path: '/servicios/informes/prevision-costes',
        icon: 'TrendingDown',
        status: 'new',
        description: 'Proyección de costes medios para el portfolio activo',
      },
      {
        id: 'svc-inf-registro-log',
        label: 'Registro Log',
        path: '/servicios/informes/registro-log',
        icon: 'ScrollText',
        status: 'new',
        description: 'Log de actividad del sistema y acciones de usuarios',
      },
      {
        id: 'svc-inf-rent-op',
        label: 'Rentabilidad de Operarios',
        path: '/servicios/informes/rentabilidad-operarios',
        icon: 'TrendingUp',
        status: 'partial',
        description: 'Rentabilidad por operario: ingresos, costes y margen',
      },
      {
        id: 'svc-inf-rent-op-cia',
        label: 'Rentabilidad Operarios/Compañías',
        path: '/servicios/informes/rentabilidad-companias',
        icon: 'BarChart2',
        status: 'new',
        description: 'Cruce de rentabilidad entre operarios y compañías',
      },
      {
        id: 'svc-inf-rent-trabajos',
        label: 'Rentabilidad Trabajos/Compañías',
        path: '/servicios/informes/rentabilidad-trabajos',
        icon: 'BarChart2',
        status: 'new',
        description: 'Rentabilidad por tipo de trabajo, operario y compañía',
      },
      {
        id: 'svc-inf-saldos',
        label: 'Saldos',
        path: '/servicios/informes/saldos',
        icon: 'Landmark',
        status: 'new',
        description: 'Saldos pendientes de cobro/pago por compañía',
      },
      {
        id: 'svc-inf-trabajos-noliq',
        label: 'Trabajos No Liquidados',
        path: '/servicios/informes/trabajos-no-liquidados',
        icon: 'PackageSearch',
        status: 'new',
        description: 'Trabajos finalizados pendientes de liquidación económica',
      },
      {
        id: 'svc-inf-trabajos-sub',
        label: 'Trabajos Subsanados',
        path: '/servicios/informes/trabajos-subsanados',
        icon: 'RotateCcw',
        status: 'new',
        description: 'Trabajos que han requerido subsanación o revisita',
      },
      {
        id: 'svc-inf-vacaciones',
        label: 'Vacaciones de Operarios',
        path: '/servicios/informes/vacaciones-operarios',
        icon: 'Palmtree',
        status: 'new',
        description: 'Calendario de vacaciones y ausencias de operarios',
      },
      {
        id: 'svc-inf-vis-pre-pend',
        label: 'Visitas Presupuestos Pendientes',
        path: '/servicios/informes/visitas-presupuestos-pendientes',
        icon: 'FileQuestion',
        status: 'new',
        description: 'Visitas finalizadas con presupuesto aún no enviado',
      },
      {
        id: 'svc-inf-vis-pre-apr',
        label: 'Visitas Presupuestos por Aprobar',
        path: '/servicios/informes/visitas-presupuestos-aprobar',
        icon: 'FileClock',
        status: 'new',
        description: 'Presupuestos enviados pendientes de aprobación',
      },
      {
        id: 'svc-inf-vis-activas',
        label: 'Visitas en Domicilio',
        path: '/servicios/informes/visitas-activas-domicilio',
        icon: 'Home',
        status: 'new',
        description: 'Visitas activas en domicilio pendientes de finalizar parte',
      },
      // — Autofacturas INTERPWGS —
      {
        id: 'svc-autofacturas-interpwgs',
        label: 'Autofacturas INTERPWGS',
        path: '/servicios/autofacturas-interpwgs',
        icon: 'RefreshCw',
        status: 'new',
        description: 'Gestión de autofacturas recibidas desde INTERPWGS',
      },
      // — Web Multiasistencia —
      {
        id: 'svc-multiasistencia',
        label: 'Web Multiasistencia',
        path: '/servicios/multiasistencia',
        icon: 'Globe',
        status: 'partial',
        description: 'Interfaz de conexión y gestión con plataforma Web Multiasistencia',
      },
      // — Avisos —
      {
        id: 'svc-asignaciones',
        label: 'Asignaciones',
        path: '/asignaciones',
        icon: 'Inbox',
        badge: { key: 'asignaciones', variant: 'info', hideWhenZero: true },
        status: 'partial',
        description: 'Avisos de asignaciones de siniestros entrantes',
      },
      {
        id: 'svc-solicitudes',
        label: 'Solicitudes',
        path: '/solicitudes',
        icon: 'Bell',
        badge: { key: 'solicitudes', variant: 'warning', hideWhenZero: true },
        status: 'partial',
        description: 'Avisos de solicitudes pendientes',
      },
      {
        id: 'svc-trabajos-no-revisados',
        label: 'Trabajos no revisados',
        path: '/partes-validacion',
        icon: 'ClipboardCheck',
        badge: { key: 'partes_pendientes', variant: 'danger', hideWhenZero: true },
        status: 'implemented',
        description: 'Listado de trabajos no revisados por el tramitador',
      },
    ],
  },

  // ── DIRECCIÓN ─────────────────────────────────────────────────────────────
  {
    id: 'direccion',
    label: 'Dirección',
    icon: 'BarChart2',
    defaultOpen: false,
    roles: REPORTING_ROLES,
    entries: [
      {
        id: 'rentabilidad',
        label: 'Rentabilidad',
        path: '/rentabilidad',
        icon: 'TrendingUp',
        roles: DIRECCION_ROLES,
        status: 'implemented',
        description: 'Análisis de rentabilidad por compañía y tipo de siniestro',
      },
      {
        id: 'informes',
        label: 'Informes',
        path: '/reporting-facturas',
        icon: 'PieChart',
        roles: REPORTING_ROLES,
        status: 'implemented',
        description: 'Reporting de facturación y producción',
      },
    ],
  },
];

// ─── FEATURE FLAGS ─────────────────────────────────────────────────────────────
// Flags activos (true = visible). Falsos ocultan el módulo aunque el rol lo permita.
// En el futuro esto puede venir de Supabase (tabla feature_flags) por tenant.
export const FEATURE_FLAGS: Record<string, boolean> = {
  planning_geografico: true,
  rentings: false,
  bancos: true,
  encuestas: false,
  autocita: false,
};

/**
 * Devuelve true si el feature flag está activo o no está definido.
 */
export function isFeatureEnabled(flag?: string): boolean {
  if (!flag) return true;
  return FEATURE_FLAGS[flag] ?? false;
}
