// ─── NAVIGATION CONFIG ──────────────────────────────────────────────────────
// Fuente de verdad de la navegación del backoffice.
// Define sidebar, grupos, cockpit y estado de implementación de cada módulo.
// NO contiene lógica de negocio ni lógica de UI.

import type { NavGroup, CockpitModuleConfig } from './types';
import {
  OPS_ROLES,
  FINANCE_ROLES,
  DIRECCION_ROLES,
  REPORTING_ROLES,
  PERITO_ACCESS,
  OPERARIO_ACCESS,
} from './permissions';

// ─── COCKPIT SUPERIOR (3 módulos grandes) ────────────────────────────────────

export const COCKPIT_MODULES: CockpitModuleConfig[] = [
  {
    id: 'asignaciones',
    label: 'Asignaciones',
    path: '/asignaciones',
    icon: 'Inbox',
    feedKey: 'asignaciones',
    variant: 'blue',
    quickFilters: [
      { label: 'Sin asignar', value: 'NO_ASIGNADO' },
      { label: 'En planificación', value: 'EN_PLANIFICACION' },
      { label: 'Urgentes', value: 'urgente' },
      { label: 'Vencidos', value: 'vencido' },
    ],
    status: 'partial',
  },
  {
    id: 'solicitudes',
    label: 'Solicitudes / Avisos',
    path: '/solicitudes',
    icon: 'Bell',
    feedKey: 'solicitudes',
    variant: 'amber',
    quickFilters: [
      { label: 'Pendientes', value: 'pendiente' },
      { label: 'Urgentes', value: 'urgente' },
      { label: 'Hoy', value: 'hoy' },
    ],
    status: 'partial',
  },
  {
    id: 'trabajos_no_revisados',
    label: 'Trabajos no revisados',
    path: '/partes-validacion',
    icon: 'ClipboardCheck',
    feedKey: 'trabajos_no_revisados',
    variant: 'red',
    quickFilters: [
      { label: 'Pendientes', value: 'pendiente' },
      { label: 'Rechazados', value: 'rechazado' },
    ],
    status: 'implemented',
  },
];

// ─── SIDEBAR — GRUPOS Y ENTRADAS ─────────────────────────────────────────────

export const NAV_GROUPS: NavGroup[] = [
  // ── ENTRADA ──────────────────────────────────────────────────────────────
  {
    id: 'entrada',
    label: 'Entrada',
    icon: 'Inbox',
    defaultOpen: true,
    entries: [
      {
        id: 'asignaciones',
        label: 'Asignaciones',
        path: '/asignaciones',
        icon: 'Inbox',
        badge: { key: 'asignaciones', variant: 'info', hideWhenZero: true },
        status: 'partial',
        description: 'Expedientes sin asignar o en planificación pendientes de acción',
      },
      {
        id: 'solicitudes',
        label: 'Solicitudes / Avisos',
        path: '/solicitudes',
        icon: 'Bell',
        badge: { key: 'solicitudes', variant: 'warning', hideWhenZero: true },
        status: 'partial',
        description: 'Alertas, avisos y solicitudes entrantes',
      },
      {
        id: 'comunicaciones',
        label: 'Comunicaciones',
        path: '/comunicaciones',
        icon: 'MessageSquare',
        badge: { key: 'comunicaciones', variant: 'default', hideWhenZero: true },
        status: 'partial',
        description: 'Bandeja de comunicaciones con asegurados y compañías',
      },
    ],
  },

  // ── OPERACIONES ───────────────────────────────────────────────────────────
  {
    id: 'operaciones',
    label: 'Operaciones',
    icon: 'FolderOpen',
    defaultOpen: true,
    entries: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        path: '/dashboard',
        icon: 'LayoutDashboard',
        status: 'implemented',
        description: 'Panel de mando con KPIs operativos y financieros',
      },
      {
        id: 'siniestros',
        label: 'Siniestros',
        path: '/expedientes',
        icon: 'FolderOpen',
        status: 'implemented',
        description: 'Todos los expedientes activos del ERP',
      },
      {
        id: 'siniestros-activos',
        label: 'Activos',
        path: '/expedientes?estado=EN_CURSO',
        icon: 'Activity',
        status: 'partial',
        description: 'Expedientes en curso activamente',
      },
      {
        id: 'siniestros-pendientes',
        label: 'Pendientes',
        path: '/expedientes?estado=PENDIENTE',
        icon: 'Clock',
        status: 'partial',
        description: 'Expedientes bloqueados a la espera de algo',
      },
      {
        id: 'siniestros-finalizados',
        label: 'Finalizados',
        path: '/expedientes?estado=FINALIZADO',
        icon: 'CheckCircle',
        status: 'partial',
        description: 'Expedientes listos para facturar',
      },
      {
        id: 'partes-validacion',
        label: 'Trabajos no revisados',
        path: '/partes-validacion',
        icon: 'ClipboardCheck',
        badge: { key: 'partes_pendientes', variant: 'danger', hideWhenZero: true },
        status: 'implemented',
        description: 'Partes de operario pendientes de validación',
      },
      {
        id: 'informes-caducados',
        label: 'Informes caducados',
        path: '/informes-caducados',
        icon: 'AlertTriangle',
        badge: { key: 'informes_caducados', variant: 'warning', hideWhenZero: true },
        status: 'implemented',
        description: 'Citas con visita realizada sin informe presentado',
      },
      {
        id: 'presupuestos',
        label: 'Presupuestos',
        path: '/presupuestos',
        icon: 'FileText',
        status: 'partial',
        description: 'Lista de presupuestos (detalle ya implementado)',
      },
    ],
  },

  // ── PLANNING ──────────────────────────────────────────────────────────────
  {
    id: 'planning',
    label: 'Planning',
    icon: 'Calendar',
    defaultOpen: false,
    entries: [
      {
        id: 'agenda-mensual',
        label: 'Agenda mensual',
        path: '/planning/agenda',
        icon: 'CalendarDays',
        status: 'new',
        description: 'Agenda operativa mensual de citas y visitas',
      },
      {
        id: 'vp-agenda',
        label: 'VP Agenda',
        path: '/videoperitaciones/agenda',
        icon: 'Video',
        status: 'implemented',
        description: 'Agenda de videoperitaciones programadas',
      },
      {
        id: 'vp-lista',
        label: 'Videoperitaciones',
        path: '/videoperitaciones',
        icon: 'Monitor',
        status: 'implemented',
        description: 'Lista de videoperitaciones activas y pendientes',
      },
      {
        id: 'vp-pendientes',
        label: 'VP Pendientes contacto',
        path: '/videoperitaciones/pendientes',
        icon: 'PhoneMissed',
        status: 'implemented',
        description: 'Videoperitaciones pendientes de primer contacto',
      },
      {
        id: 'planning-geografico',
        label: 'Planning geográfico',
        path: '/planning/geo',
        icon: 'MapPin',
        status: 'implemented',
        description: 'Mapa operativo de expedientes, operarios y Smart Dispatch',
      },
    ],
  },

  // ── RED EXTERNA ───────────────────────────────────────────────────────────
  {
    id: 'red-externa',
    label: 'Red externa',
    icon: 'Users',
    defaultOpen: false,
    entries: [
      {
        id: 'operarios',
        label: 'Operarios',
        path: '/operarios-config',
        icon: 'HardHat',
        roles: OPERARIO_ACCESS,
        status: 'partial',
        description: 'Gestión de operarios propios y subcontratados',
      },
      {
        id: 'proveedores',
        label: 'Proveedores',
        path: '/proveedores',
        icon: 'Truck',
        status: 'implemented',
        description: 'Catálogo de proveedores de materiales y servicios',
      },
      {
        id: 'peritos',
        label: 'Peritos',
        path: '/peritos/admin',
        icon: 'UserSearch',
        roles: PERITO_ACCESS,
        status: 'implemented',
        description: 'Gestión de peritos y asignación de expedientes',
      },
      {
        id: 'peritos-expedientes',
        label: 'Mis expedientes (Perito)',
        path: '/peritos/expedientes',
        icon: 'ClipboardList',
        roles: ['perito', 'admin', 'supervisor'],
        status: 'implemented',
        description: 'Expedientes asignados al perito autenticado',
      },
      {
        id: 'peritos-dictamenes',
        label: 'Dictámenes',
        path: '/peritos/dictamenes',
        icon: 'Scale',
        roles: PERITO_ACCESS,
        status: 'implemented',
        description: 'Informes de valoración y dictámenes periciales',
      },
      {
        id: 'clientes',
        label: 'Clientes / Intervinientes',
        path: '/clientes',
        icon: 'UserCircle',
        status: 'new',
        description: 'Asegurados, propietarios y terceros intervinientes',
      },
      {
        id: 'rentings',
        label: 'Rentings',
        path: '/rentings',
        icon: 'Building2',
        featureFlag: 'rentings',
        status: 'new',
        description: 'Gestión de contratos de renting asociados a siniestros',
      },
    ],
  },

  // ── BUZÓN CORREO ──────────────────────────────────────────────────────────
  {
    id: 'correo',
    label: 'Buzón Correo',
    icon: 'Mail',
    defaultOpen: false,
    roles: OPS_ROLES,
    entries: [
      {
        id: 'correo-cuentas',
        label: 'Cuentas correo',
        path: '/correo/cuentas',
        icon: 'AtSign',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Cuentas IMAP/SMTP configuradas para el sistema',
      },
      {
        id: 'correo-configuracion',
        label: 'Configuración correo',
        path: '/correo/configuracion',
        icon: 'Settings2',
        roles: ['admin', 'supervisor'],
        status: 'new',
        description: 'SMTP, Resend, plantillas y reglas de enrutamiento',
      },
    ],
  },

  // ── FINANZAS ──────────────────────────────────────────────────────────────
  {
    id: 'finanzas',
    label: 'Finanzas',
    icon: 'DollarSign',
    defaultOpen: false,
    roles: FINANCE_ROLES,
    entries: [
      {
        id: 'pendientes-facturar',
        label: 'Pendientes de facturar',
        path: '/pendientes-facturar',
        icon: 'Receipt',
        badge: { key: 'facturas_pendientes', variant: 'warning', hideWhenZero: true },
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Expedientes finalizados pendientes de emitir factura',
      },
      {
        id: 'facturas',
        label: 'Facturas',
        path: '/facturas',
        icon: 'FileText',
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Listado de facturas emitidas',
      },
      {
        id: 'facturas-caducadas',
        label: 'Facturas caducadas',
        path: '/facturas-caducadas',
        icon: 'FileMinus',
        badge: { key: 'facturas_caducadas', variant: 'danger', hideWhenZero: true },
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Facturas vencidas sin cobrar o con anomalías',
      },
      {
        id: 'autofacturas',
        label: 'Autofacturas',
        path: '/autofacturas',
        icon: 'RefreshCw',
        roles: FINANCE_ROLES,
        status: 'implemented',
        description: 'Autofacturas de operarios y peritos',
      },
      {
        id: 'pedidos',
        label: 'Pedidos',
        path: '/pedidos',
        icon: 'ShoppingCart',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Órdenes de compra de materiales a proveedores',
      },
      {
        id: 'pedidos-recoger',
        label: 'Pedidos a recoger',
        path: '/pedidos/a-recoger',
        icon: 'Package',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Materiales pendientes de recogida en almacén',
      },
      {
        id: 'pedidos-caducados',
        label: 'Pedidos caducados',
        path: '/pedidos/caducados',
        icon: 'PackageX',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Pedidos sin gestionar fuera de plazo',
      },
      {
        id: 'config-emision',
        label: 'Config. emisión',
        path: '/config-emision',
        icon: 'Layers',
        roles: ['admin', 'financiero', 'supervisor'],
        status: 'implemented',
        description: 'Series, numeración, asignaciones, cuentas bancarias y config. de emisión por empresa',
      },
      {
        id: 'series-facturacion',
        label: 'Series facturación',
        path: '/series-facturacion',
        icon: 'Hash',
        roles: ['admin', 'financiero', 'supervisor'],
        status: 'partial',
        description: 'Configuración de series y numeración de facturas por empresa',
      },
      {
        id: 'bancos',
        label: 'Bancos',
        path: '/bancos',
        icon: 'Landmark',
        roles: FINANCE_ROLES,
        featureFlag: 'bancos',
        status: 'partial',
        description: 'Cuentas bancarias y conciliación de cobros',
      },
    ],
  },

  // ── CONTROL ───────────────────────────────────────────────────────────────
  {
    id: 'control',
    label: 'Control',
    icon: 'Sliders',
    defaultOpen: false,
    entries: [
      {
        id: 'baremos',
        label: 'Baremos',
        path: '/baremos',
        icon: 'BookOpen',
        roles: ['admin', 'supervisor', 'tramitador', 'financiero'],
        status: 'implemented',
        description: 'Catálogo de baremos y tarifas de trabajo',
      },
      {
        id: 'tareas',
        label: 'Tareas',
        path: '/tareas',
        icon: 'CheckSquare',
        badge: { key: 'tareas', variant: 'info', hideWhenZero: true },
        status: 'implemented',
        description: 'Gestión de tareas internas y externas',
      },
      {
        id: 'eventos',
        label: 'Eventos / Automatizaciones',
        path: '/eventos',
        icon: 'Zap',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Reglas de negocio, triggers y automatizaciones del ERP',
      },
      {
        id: 'mensajes-predefinidos',
        label: 'Mensajes predefinidos',
        path: '/mensajes-predefinidos',
        icon: 'MessageCircle',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Plantillas de comunicación para email y SMS con variables dinámicas',
      },
      {
        id: 'encuestas',
        label: 'Encuestas',
        path: '/encuestas',
        icon: 'ClipboardList',
        roles: OPS_ROLES,
        status: 'implemented',
        description: 'Encuestas de satisfacción de cliente (post-cierre)',
      },
      {
        id: 'condiciones-control',
        label: 'Condiciones Presupuestos',
        path: '/condiciones-presupuestos',
        icon: 'FileText',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Textos de condiciones para presupuestos',
      },
      {
        id: 'documentos',
        label: 'Documentos',
        path: '/control/documentos',
        icon: 'FolderArchive',
        status: 'new',
        description: 'Gestión documental centralizada (Storage Supabase)',
      },
      {
        id: 'auditoria',
        label: 'Auditoría',
        path: '/control/auditoria',
        icon: 'Shield',
        roles: ['admin', 'supervisor', 'direccion'],
        status: 'new',
        description: 'Trazabilidad de acciones y log de auditoría del sistema',
      },
    ],
  },

  // ── CONFIGURACIÓN ─────────────────────────────────────────────────────────
  {
    id: 'configuracion',
    label: 'Configuración',
    icon: 'Settings',
    defaultOpen: false,
    roles: ['admin', 'supervisor'],
    entries: [
      {
        id: 'usuarios-roles',
        label: 'Tramitadores',
        path: '/usuarios',
        icon: 'UserCog',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Alta, edición y configuración de tramitadores internos',
      },
      {
        id: 'cargas-trabajo',
        label: 'Cargas de trabajo',
        path: '/usuarios/cargas',
        icon: 'LayoutDashboard',
        roles: ['admin', 'supervisor', 'direccion'],
        status: 'implemented',
        description: 'Dashboard de carga actual por tramitador en tiempo real',
      },
      {
        id: 'cola-asignacion',
        label: 'Cola de asignación',
        path: '/usuarios/cola',
        icon: 'ListOrdered',
        roles: ['admin', 'supervisor'],
        badge: { key: 'cola_asignacion', variant: 'warning', hideWhenZero: true },
        status: 'implemented',
        description: 'Expedientes sin tramitador asignado pendientes de gestión',
      },
      {
        id: 'reglas-reparto',
        label: 'Reglas de reparto',
        path: '/usuarios/reglas-reparto',
        icon: 'Shuffle',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Algoritmos de asignación automática y preasignaciones',
      },
      {
        id: 'companias',
        label: 'Compañías / Corredores / AF',
        path: '/companias',
        icon: 'Building',
        roles: ['admin', 'supervisor'],
        status: 'partial',
        description: 'Entidades aseguradoras, corredores y agencias franquiciadas',
      },
      {
        id: 'empresas',
        label: 'Empresas',
        path: '/empresas',
        icon: 'Briefcase',
        roles: ['admin', 'supervisor'],
        status: 'partial',
        description: 'Empresas facturadoras propias del grupo',
      },
      {
        id: 'especialidades',
        label: 'Especialidades',
        path: '/especialidades',
        icon: 'Wrench',
        roles: ['admin', 'supervisor'],
        status: 'partial',
        description: 'Tipos de siniestro, especialidades técnicas y gremios',
      },
      {
        id: 'calendario',
        label: 'Festivos',
        path: '/festivos',
        icon: 'CalendarRange',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Calendario de festivos nacionales, autonómicos y de empresa',
      },
      {
        id: 'comerciales',
        label: 'Comerciales',
        path: '/comerciales',
        icon: 'UserPlus',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Agentes comerciales e intermediarios del sistema',
      },
      {
        id: 'gestor-tipos',
        label: 'Gestor de Tipos',
        path: '/gestor-tipos',
        icon: 'Tag',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Tipos y etiquetas de clasificación de siniestros',
      },
      {
        id: 'doc-requerida',
        label: 'Doc. Requerida',
        path: '/doc-requerida',
        icon: 'FileCheck2',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Tipos de documentos exigidos a los operarios',
      },
      {
        id: 'autocita',
        label: 'Autocita',
        path: '/autocita',
        icon: 'Link',
        roles: ['admin', 'supervisor'],
        featureFlag: 'autocita',
        status: 'partial',
        description: 'Configuración del portal de autocita para asegurados',
      },
      {
        id: 'condiciones-presupuestos',
        label: 'Condiciones Presupuestos',
        path: '/condiciones-presupuestos',
        icon: 'FileText',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Textos de condiciones incluidos en presupuestos',
      },
      {
        id: 'centralita',
        label: 'Centralita',
        path: '/centralita',
        icon: 'Phone',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Registro de llamadas e integración de centralita',
      },
      {
        id: 'rgpd',
        label: 'RGPD',
        path: '/rgpd',
        icon: 'Shield',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Configuración de protección de datos y derechos de supresión',
      },
      {
        id: 'auto-visitas',
        label: 'Auto Visitas',
        path: '/auto-visitas',
        icon: 'Link2',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Portal de cita automática para asegurados',
      },
      {
        id: 'acerca-de',
        label: 'Acerca de GUAI ERP',
        path: '/acerca-de',
        icon: 'Info',
        roles: ['admin', 'supervisor'],
        status: 'implemented',
        description: 'Versión del sistema, stack tecnológico y soporte',
      },
    ],
  },

  // ── DIRECCIÓN ─────────────────────────────────────────────────────────────
  {
    id: 'direccion',
    label: 'Dirección',
    icon: 'BarChart2',
    defaultOpen: false,
    roles: REPORTING_ROLES,
    entries: [
      {
        id: 'rentabilidad',
        label: 'Rentabilidad',
        path: '/rentabilidad',
        icon: 'TrendingUp',
        roles: DIRECCION_ROLES,
        status: 'implemented',
        description: 'Análisis de rentabilidad por compañía y tipo de siniestro',
      },
      {
        id: 'informes',
        label: 'Informes',
        path: '/reporting-facturas',
        icon: 'PieChart',
        roles: REPORTING_ROLES,
        status: 'implemented',
        description: 'Reporting de facturación y producción',
      },
    ],
  },
];

// ─── FEATURE FLAGS ─────────────────────────────────────────────────────────────
// Flags activos (true = visible). Falsos ocultan el módulo aunque el rol lo permita.
// En el futuro esto puede venir de Supabase (tabla feature_flags) por tenant.
export const FEATURE_FLAGS: Record<string, boolean> = {
  planning_geografico: true,
  rentings: false,
  bancos: true,
  encuestas: false,
  autocita: false,
};

/**
 * Devuelve true si el feature flag está activo o no está definido.
 */
export function isFeatureEnabled(flag?: string): boolean {
  if (!flag) return true;
  return FEATURE_FLAGS[flag] ?? false;
}
