BEGIN;

-- ════════════════════════════════════════════════════════════════════════
-- Fix: vp_documento_final, vp_facturas, vp_envios — RLS hardening
--
-- Migration 00016 created USING (true) policies that grant full read/write
-- access to any authenticated user regardless of role.
-- This migration drops those permissive policies and replaces them with
-- role-specific access aligned with the EP-11B security model.
--
-- Depends on:
--   public.has_any_role()     — from 00018_sprint55_phase0_rls_hardening.sql
--   public.can_access_vp()    — from 20260318213000_fix_vp_perito_rls.sql
--   public.current_perito_id() — from 20260318213000_fix_vp_perito_rls.sql
-- ════════════════════════════════════════════════════════════════════════


-- ─── 1. vp_documento_final ────────────────────────────────────────────
--
-- Old: SELECT/INSERT/UPDATE → TO authenticated USING (true)
-- New:
--   SELECT  → office roles (admin, supervisor, tramitador, financiero, direccion)
--             + assigned perito via can_access_vp (read-only, for delivery confirmation)
--   INSERT  → office roles only (generated by EP-11B flow)
--   UPDATE  → restricted office roles (admin, supervisor, financiero, direccion)

-- Drop old names (migration 00016 originals)
DROP POLICY IF EXISTS vp_documento_final_select        ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_insert        ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_update        ON vp_documento_final;
-- Drop names that may exist in remote if previously partially patched
DROP POLICY IF EXISTS vp_documento_final_select_scoped ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_manage_scoped ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_update_scoped ON vp_documento_final;
-- Drop canonical target names (idempotent re-run safety)
DROP POLICY IF EXISTS vp_documento_final_office_select ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_perito_select ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_office_insert ON vp_documento_final;
DROP POLICY IF EXISTS vp_documento_final_office_update ON vp_documento_final;

CREATE POLICY vp_documento_final_office_select
  ON vp_documento_final FOR SELECT
  USING (public.has_any_role(ARRAY['admin','supervisor','tramitador','financiero','direccion']));

CREATE POLICY vp_documento_final_perito_select
  ON vp_documento_final FOR SELECT
  USING (
    public.current_perito_id() IS NOT NULL
    AND public.can_access_vp(videoperitacion_id)
  );

CREATE POLICY vp_documento_final_office_insert
  ON vp_documento_final FOR INSERT
  WITH CHECK (public.has_any_role(ARRAY['admin','supervisor','tramitador','financiero','direccion']));

CREATE POLICY vp_documento_final_office_update
  ON vp_documento_final FOR UPDATE
  USING (public.has_any_role(ARRAY['admin','supervisor','financiero','direccion']));


-- ─── 2. vp_facturas ───────────────────────────────────────────────────
--
-- Old: SELECT/INSERT → TO authenticated USING (true)
-- New:
--   SELECT  → finance + office management only
--             (tramitador excluded: facturas VP are commercial data)
--   INSERT  → finance only (admin, financiero)
--   No UPDATE policy: factura lines are immutable after emission

-- Drop old names (migration 00016 originals)
DROP POLICY IF EXISTS vp_facturas_select         ON vp_facturas;
DROP POLICY IF EXISTS vp_facturas_insert         ON vp_facturas;
-- Drop names that may exist in remote if previously partially patched
DROP POLICY IF EXISTS vp_facturas_staff_select   ON vp_facturas;
DROP POLICY IF EXISTS vp_facturas_finance_insert ON vp_facturas;
-- Drop canonical target names (idempotent re-run safety)
DROP POLICY IF EXISTS vp_facturas_finance_select ON vp_facturas;

CREATE POLICY vp_facturas_finance_select
  ON vp_facturas FOR SELECT
  USING (public.has_any_role(ARRAY['admin','supervisor','financiero','direccion']));

CREATE POLICY vp_facturas_finance_insert
  ON vp_facturas FOR INSERT
  WITH CHECK (public.has_any_role(ARRAY['admin','financiero']));


-- ─── 3. vp_envios ─────────────────────────────────────────────────────
--
-- Old: SELECT/INSERT/UPDATE → TO authenticated USING (true)
-- Note: 20260318213000 already added vp_envios_perito_select (USING can_access_vp).
--       That policy is correct and is NOT touched here.
--       We only replace the overly-permissive base policies.
-- New:
--   SELECT  → office roles (perito access via existing vp_envios_perito_select)
--   INSERT  → office roles (tramitador and above can initiate sends)
--   UPDATE  → restricted roles only (retry, acknowledge — not tramitador)

-- Drop old names (migration 00016 originals)
DROP POLICY IF EXISTS vp_envios_select          ON vp_envios;
DROP POLICY IF EXISTS vp_envios_insert          ON vp_envios;
DROP POLICY IF EXISTS vp_envios_update          ON vp_envios;
-- Drop names that may exist in remote if previously partially patched
DROP POLICY IF EXISTS vp_envios_staff_select    ON vp_envios;
DROP POLICY IF EXISTS vp_envios_finance_insert  ON vp_envios;
DROP POLICY IF EXISTS vp_envios_finance_update  ON vp_envios;
DROP POLICY IF EXISTS vp_envios_perito_select   ON vp_envios;
-- Drop canonical target names (idempotent re-run safety)
DROP POLICY IF EXISTS vp_envios_office_select   ON vp_envios;
DROP POLICY IF EXISTS vp_envios_office_insert   ON vp_envios;
DROP POLICY IF EXISTS vp_envios_office_update   ON vp_envios;

CREATE POLICY vp_envios_perito_select
  ON vp_envios FOR SELECT
  USING (
    public.current_perito_id() IS NOT NULL
    AND public.can_access_vp(videoperitacion_id)
  );

CREATE POLICY vp_envios_office_select
  ON vp_envios FOR SELECT
  USING (public.has_any_role(ARRAY['admin','supervisor','tramitador','financiero','direccion']));

CREATE POLICY vp_envios_office_insert
  ON vp_envios FOR INSERT
  WITH CHECK (public.has_any_role(ARRAY['admin','supervisor','tramitador','financiero','direccion']));

CREATE POLICY vp_envios_office_update
  ON vp_envios FOR UPDATE
  USING (public.has_any_role(ARRAY['admin','supervisor','financiero','direccion']));


COMMIT;
